import { ReactNode } from 'react';
import Provider from '@/components/Provider';
import './globals.css';

interface IRootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang='en'>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
